version: '3'
services:

  mongo:
    image: mongo
    restart: "always"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    depends_on: 
      - mongo

  consul:
    image: consul
    environment:
      CONSUL_BIND_INTERFACE : eth0

  api-balancer:
    build:
      context: ./packages/balancer
      dockerfile: Dockerfile.dev
    volumes:
      - ./packages/balancer:/app
    ports:
      - "5050:5050"

  api:
    build:
      context: ./packages/api/
      dockerfile: Dockerfile.dev
    volumes:
      - ./packages/api:/app
    ports:
      - "3000-3010:3000"
    restart: "always"
    depends_on: 
      - mongo
      - consul

  nginx:
    image: nginx:alpine
    ports: 
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro


  