version: '3'
services:

  mongo:
    image: mongo
    restart: "always"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    depends_on: 
      - mongo

  consul:
    image: consul
    logging:
      driver: none
    environment:
      CONSUL_BIND_INTERFACE : eth0

  api-gateway:
    build:
      context: ./packages/gateway
      dockerfile: Dockerfile.dev
    environment:
      PROXY_TARGET_TAG : "api"
      PORT: 5050
    volumes:
      - ./packages/gateway:/app
    ports:
      - "5050:5050"
      
  web-app-gateway:
    build:
      context: ./packages/gateway
      dockerfile: Dockerfile.dev
    environment:
      PROXY_TARGET_TAG : "web-app"
      OVERRIDE_TARGET_PORT: 3000
      PORT: 5051
    volumes:
      - ./packages/gateway:/app
    ports:
      - "5051:5051"

  api:
    build:
      context: ./packages/api/
      dockerfile: Dockerfile.dev
    volumes:
      - ./packages/api:/app
    ports:
      - "4000-4010:3000"
    environment:
      PORT: 3000
    restart: "always"
    depends_on: 
      - mongo
      - consul

  web-app:
    restart: "always"
    build:
      context: ./packages/web/
      dockerfile: Dockerfile.dev
    volumes:
      - ./packages/web:/app     
    environment:
      NODE_ENV: "development"
      BS_PORT: 3000
      PORT: 3010
    depends_on:
      - api     

  nginx:
    build:
      context: ./nginx/
    restart: always
    ports:
      - "3000:80"
    logging:
      driver: none


  